name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Syntax check (compile Python files)
        run: |
          python - <<'PY'
          import sys, compileall
          ok = compileall.compile_dir('.', force=False, quiet=1)
          if not ok:
              sys.exit(1)
          PY

      - name: Run tests (pytest) if present
        shell: bash -l {0}
        run: |
          # Robust test detection:
          # - If there is a tests/ directory or any test_*.py files at repo root, run pytest.
          # - Otherwise skip pytest. Any pytest failures will still fail the job.
          if [ -d tests ] || ls test_*.py >/dev/null 2>&1; then
            echo "Test files detected: running pytest"
            pytest -q
          else
            echo "No tests found, skipping pytest"
          fi

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t dqn-gridworld:ci .